theme: jekyll-theme-minimal
highlighter: rouge
markdown: kramdown


title: Claire Ryan
description: Blog

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /:title/
