theme: jekyll-theme-minimal
highlighter: rouge
markdown: kramdown


title: Claire Ryan
description: Blog
baseurl: https://clryan.github.io
plugins:
  - jekyll-seo-tag

# Site owner
owner:
  name: Claire Ryan
  avatar: /assets/img/headshot.png
  bio:
  position: Senior Data Analyst
  company_name: DaVita
  company_url: https://www.davita.com/
  place_name: St. Paul, MN
  email: ryan.claire29@gmail.com
  disqus-shortname:
  twitter: DataClaireMN
  google:
    plus: #username
    analytics:
  github: clryan
  stackoverflow:
  linkedin: cl-ryan

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
