theme: jekyll-theme-minimal
highlighter: rouge
markdown: kramdown

# Personal attributes

name: Claire Ryan
title: Claire Ryan
description: Blog

# Defaults

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /:title/
