theme: jekyll-theme-minimal
highlighter: rouge
markdown: kramdown

# Personal attributes

name: Claire Ryan
title: Claire Ryan
description: Blog
jobtitle: Senior Data Analyst
company_name: DaVita
company_icon: https://www.davita.com/favicon.png
company_url: https://www.davita.com/
location: Saint Paul, MN
headshot: /assets/img/headshot.png

# Social

linkedin: cl-ryan
github: clryan
twitter: DataClaireMN
email: ryan.claire29@gmail.com

# Defaults

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /:title/
